name = "so-template-hub"
main = "index.js"
compatibility_date = "2026-09-01"

[vars]
REPO = "namelessone88/story-oracle-templates"

[[kv_namespaces]]
binding = "RL"
id = "b4be2490c0074626bd4be1afcd92b6c6"
